# Generated by Django 5.0.6 on 2024-06-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_blog_created_date_blog_draft"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employeemodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empname", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("salar", models.IntegerField()),
            ],
            options={
                "db_table": "employee",
            },
        ),
    ]
