# Generated by Django 5.0.6 on 2024-06-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="Blog Images"),
        ),
    ]
